-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 19:53:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema StoredProcedures
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StoredProcedures
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StoredProcedures` ;
USE `StoredProcedures` ;

-- -----------------------------------------------------
-- Table `StoredProcedures`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoredProcedures`.`Cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoredProcedures`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoredProcedures`.`Alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `endereco` VARCHAR(150) NULL,
  `ra` INT NOT NULL,
  `email` VARCHAR(90) NULL,
  `Cursos_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `Cursos_id_curso`),
  INDEX `fk_Alunos_Cursos1_idx` (`Cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_Cursos1`
    FOREIGN KEY (`Cursos_id_curso`)
    REFERENCES `StoredProcedures`.`Cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoredProcedures`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoredProcedures`.`Professores` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `endereco` VARCHAR(150) NULL,
  `Cursos_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_professor`, `Cursos_id_curso`),
  INDEX `fk_Professores_Cursos1_idx` (`Cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Professores_Cursos1`
    FOREIGN KEY (`Cursos_id_curso`)
    REFERENCES `StoredProcedures`.`Cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
